### ISSUE TITLE
Make pypi release

### ISSUE THREAD

**Issue by frankwiles** [revsys/jslog4kube#3]

**Comment by halkeye** [comment]
Yea! this is awesome.

I found https://pypi.python.org/pypi/zest.releaser one of the easiest ways to do releases, but anything you could do to make it pypi instead of a github link would be 👍 from me.

Let me know how I can help.

**Comment by rosscdh** [comment]
+1 https://pypi.org/project/twine/ is what you want to use .. simple

**Comment by frankwiles** [comment]
It took me forever to get around to it, but 1.0.4 and 1.0.5 are now on PyPI https://pypi.org/project/jslog4kube/
